### PR TITLE
Fix CRUD issues in VUE App

### LINKED ISSUE #107: [Bug] Fix CRUD issues in VUE App

### PR DESCRIPTION
**Pull request by ghost**
Resolves: #107 
Here is the loom:
https://www.loom.com/share/598b3d6deca34a978d919117c15e2206

### CODE REVIEW

File: src/vuexTemplates/store/modules/users.js [hunk 1]
```diff
@@ -11,10 +11,10 @@ const getters = {
     return state.selectedUser;
   },
 };
-
+let userId = 0
 const actions = {
```
Comment (manjeetbeniwalinnostax) [inline src/vuexTemplates/store/modules/users.js:15]: Will replace the functionality of generating userId by using the UUID in another PR.

**Review by manjeetbeniwalinnostax — APPROVED** [review]

**Review by manjeetbeniwalinnostax — APPROVED** [review]

**Review by himanshuinnostax — APPROVED** [review]
